Depth limit check
valtuutus/valtuutus pull request #50
Opened 2024-08-19 13:54 UTC by NormanFrieman

2024-08-20 14:19 UTC, yanpitangui requested changes

2024-08-20 14:47 UTC, lucasgoveia commented on src/Valtuutus.Core/Engines/DepthUtils.cs
> +        public static bool CheckDepth(this IWithDepth req) =>
> Talvez o nome não represente bem o que o método está fazendo, acho que algo como CheckDepthLimit ou similar deve dar mais sentido, o que acha @lucasgoveia?

Acho que ficaria mais claro.

2024-08-20 18:47 UTC, NormanFrieman commented on src/Valtuutus.Core/Engines/DepthUtils.cs
> +        public static bool CheckDepth(this IWithDepth req) =>
Esqueci de dar push

2024-08-20 19:20 UTC, yanpitangui approved these changes

2024-08-21 14:38 UTC, lucasgoveia approved these changes

2024-08-21 14:38 UTC, merged